# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    # session: true < ligne d origine

    session:
        enabled: true
        handler_id: null  # Utilisation du gestionnaire de session par défaut (enregistrements en fichiers)
        save_path: '%kernel.cache_dir%/sessions'  # Emplacement des fichiers de session (si stockage par défaut)

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
