symfonycasts_reset_password:
    request_password_repository: App\Repository\ResetPasswordRequestRepository
    lifetime: 900  # Durée de validité du token en secondes (1 heure par défaut) // modif fr-en dans translation.yaml
    throttle_limit: 300 # Temps minimal entre 2 demandes
